In [2]:
%pylab qt

Populating the interactive namespace from numpy and matplotlib


In [100]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import Delaunay
import scipy
from collections import OrderedDict

from Proj4.utils import *

In [175]:
class Image:
    
    def __init__(self, name, imArr, pts = None):
        self.name = name
        self.imArr = imArr
        self.pts = pts
        self.height, self.width = imArr.shape[:2]

    def fromPath(pathName):
        imArr, imName = readImageNName(pathName)
        result = Image(imName, imArr)
        return result

    def setPts(self, ptSetup):
        ptsCt = sum([x for x in ptSetup.values()])
        print("ptsCt: ", ptsCt)
        self.pts = getPoints(self, ptsCt)
        self.ptSetup = ptSetup
    
#     def refreshDims(self):
#         self.height, self.width = imArr.shape[:2]
    

In [ ]:
sum([x for x in mainPtSetup.values()])

In [176]:
imMan1, _ = readImageNName("Proj4/sample_imgs/01-2m.jpg")

imM1 = Image.fromPath("Proj4/sample_imgs/01-2m.jpg")
imM2 = Image.fromPath("Proj4/sample_imgs/05-2m.jpg")

imM1PresetPts = np.array([(310.4090909090909, 415.6038961038961), (268.8506493506494, 397.42207792207785), (244.17532467532467, 361.0584415584415), (227.2922077922078, 314.3051948051948), (224.69480519480518, 236.38311688311683), (233.7857142857143, 185.73376623376618), (263.6558441558442, 148.0714285714285), (348.07142857142856, 144.1753246753246), (381.8376623376623, 177.94155844155836), (400.01948051948057, 235.08441558441552), (397.42207792207796, 309.1103896103896), (381.8376623376623, 351.9675324675324), (354.56493506493507, 394.8246753246753), (215.60389610389612, 310.4090909090909), (202.6168831168831, 270.1493506493506), (203.9155844155844, 235.08441558441552), (200.01948051948048, 181.83766233766227), (215.60389610389612, 133.78571428571422), (248.07142857142858, 98.72077922077915), (368.8506493506494, 98.72077922077915), (406.51298701298697, 135.08441558441552), (423.3961038961039, 179.24025974025966), (415.6038961038961, 238.98051948051943), (422.0974025974026, 279.24025974025966), (411.7077922077922, 315.6038961038961), (270.1493506493506, 242.8766233766233), (350.66883116883116, 244.1753246753246), (237.68181818181816, 228.590909090909), (254.56493506493504, 216.90259740259734), (298.72077922077926, 224.6948051948051), (327.2922077922078, 225.9935064935064), (362.3571428571429, 218.20129870129864), (387.03246753246754, 229.8896103896103), (310.4090909090909, 240.27922077922074), (283.1363636363636, 296.12337662337654), (311.7077922077922, 302.61688311688306), (335.08441558441564, 297.42207792207785), (257.1623376623377, 320.79870129870125), (310.4090909090909, 329.8896103896103), (357.1623376623377, 325.9935064935064), (274.0454545454545, 337.68181818181813), (309.1103896103896, 354.564935064935), (335.08441558441564, 344.17532467532465)])
imM2PresetPts = np.array([(327.2922077922078, 389.6298701298701), (279.2402597402597, 366.2532467532467), (250.6688311688312, 320.79870129870125), (242.87662337662337, 279.24025974025966), (246.77272727272728, 220.79870129870125), (255.86363636363635, 171.4480519480519), (289.62987012987014, 124.6948051948051), (390.92857142857144, 135.08441558441552), (415.6038961038961, 183.13636363636357), (424.6948051948052, 231.18831168831161), (419.5, 297.42207792207785), (406.51298701298697, 337.68181818181813), (379.2402597402597, 374.0454545454545), (236.38311688311686, 274.0454545454545), (235.08441558441555, 245.4740259740259), (236.38311688311686, 211.70779220779212), (242.87662337662337, 154.56493506493496), (259.7597402597403, 98.72077922077915), (310.4090909090909, 62.357142857142776), (377.9415584415584, 67.55194805194793), (419.5, 105.21428571428561), (433.78571428571433, 148.0714285714285), (431.1883116883117, 231.18831168831161), (428.5909090909091, 259.75974025974017), (424.6948051948052, 285.7337662337662), (297.42207792207796, 228.590909090909), (379.2402597402597, 235.08441558441552), (267.5519480519481, 215.60389610389603), (296.12337662337666, 206.51298701298697), (325.9935064935065, 211.70779220779212), (351.96753246753246, 218.20129870129864), (376.6428571428571, 211.70779220779212), (405.2142857142858, 220.79870129870125), (336.38311688311694, 228.590909090909), (309.1103896103896, 277.94155844155836), (338.98051948051955, 285.7337662337662), (362.3571428571429, 275.3441558441558), (287.03246753246754, 301.31818181818176), (336.38311688311694, 301.31818181818176), (371.448051948052, 305.21428571428567), (305.21428571428567, 316.90259740259734), (329.8896103896104, 323.39610389610385), (358.461038961039, 319.49999999999994)])

print(imM1PresetPts.shape)
print(getCorners(imM1.imArr).shape)

imM1.pts = np.vstack((imM1PresetPts, getCorners(imM1.imArr)))
imM2.pts = np.vstack((imM2PresetPts, getCorners(imM2.imArr)))


#### Defaults
mainPtSetup = OrderedDict()
mainPtSetup['wo'] = 13
mainPtSetup['bo'] = 12
mainPtSetup['go'] = 2
mainPtSetup['co'] = 6
mainPtSetup['ro'] = 4
mainPtSetup['yo'] = 6
# side pixels setup

(43, 2)
(4, 2)


In [9]:
def getCorners(imArr):
    return np.array([(0, 0), (imArr.shape[1], 0), (0, imArr.shape[0]), (imArr.shape[1], imArr.shape[0])])

dispPtsOnImg(im1.imArr, getCorners(im1.imArr))

In [ ]:
imM1.imArr.shape

In [6]:
def getPoints(im, n):
    n = int(n)
    plt.imshow(im.imArr)
    points = plt.ginput(n, timeout = 300, show_clicks=True)
    plt.close()
    print("points gotten from", im.name, ":", str(points))
    return np.array(points)

def dispPtsOnImg(imMan1, results):
    plt.imshow(imMan1)
    plt.plot(results[:, 0], results[:, 1], 'bo')
    for x, y in results:
        plt.text(x, y, "%d-%d" % (x,y))
    plt.waitforbuttonpress()
    plt.close()

In [ ]:
results = getPoints(imMan1, 3)

In [7]:
def dispTriangulation(test_tri, im = None):
    if type(im) == np.ndarray:
        plt.imshow(im)
    plt.triplot(test_tri.points[:, 0], test_tri.points[:, 1], test_tri.simplices)
    # plt.plot(test_tri.points[:, 0], test_tri.points[:, 1])
    plt.waitforbuttonpress()
    plt.close()

In [362]:
def delaunaySmartCp(points, baseDela):
    assert len(points) == len(baseDela.points), "Number of points is not equal"
    # uses input pts, simplices
    
#     print("points:", points)
#     print("baseDela.points:", baseDela.points)
    
    newDela = Delaunay(baseDela.points.copy())
    newDela.simplices[:] = baseDela.simplices[:]
    newDela.points[:] = points
    
    return newDela
    

#def fnXX(im1, im2, ptSetup = mainPtSetup):
#     im1.setPts(ptSetup)
#     im2.setPts(ptSetup)

im1 = imM1
im2 = imM2

dispPtsOnImg(im2.imArr, im2.pts)
dispPtsOnImg(im1.imArr, im1.pts)

midPts = np.dot(im1.pts + im2.pts, 0.5)

midPtsDela = Delaunay(midPts)
im1Dela = delaunaySmartCp(im1.pts, test_tri)
# print(im1Dela.points, im1.pts)
# im1.pts[0] = [1, 1]
# print(im1Dela.points, im1.pts)
im2Dela = delaunaySmartCp(im2.pts, test_tri)

dispTriangulation(im1Dela,  im1.imArr)
dispTriangulation(im2Dela, im2.imArr)
dispTriangulation(midPtsDela, im1.imArr)
dispTriangulation(midPtsDela, im2.imArr)


# fnXX(imM1, imM2)

In [347]:
"""
given point P
find end_triangle of P
find corresponding start_triangle #should be the same index as end_triangle

calculate the transformation T from end triangle to start triangle

apply T to P to get P', which is P equivalent in start_triangle

P' is absolutely going to be in the middle of pixels, so interpolate it

put P' to P

"""






In [ ]:
dispPtsOnImg(im1.imArr, im1.pts)
dispPtsOnImg(im2.imArr, im2.pts)
im2Dela.find_simplex(np.array([289, 98])) # NOTE: x,y in matplotlib

In [359]:
plt.close()
# t1 = A
# t2 = X
clust1 = np.array([[1, 1], [4, 4], [6,1]])
# clust2 = np.array([[0, 1], [2, 1], [3,3]])
clust2 = np.array([[1, 1], [6, 6], [6,1]])
simp = np.array([[0, 1, 2]])
# clust2 = np.array([1, 2, 3])
plt.triplot(clust1[:, 0], clust1[:, 1], simp)
plt.triplot(clust2[:, 0], clust2[:, 1], simp)

def transformationMatrixFind(a_vects, x_vects):
    assert a_vects.shape == (3, 2) and x_vects.shape == (3, 2), "inputs are not triangle points of shape (3, 2)"
    
    matrixer = lambda p0, p1, p2: np.array([p0, p1, p2]).T
    # RETURNS TAKES X, Y FORMAT, RETURNS X, Y FORMAT [X, Y, 1]T

    A = np.vstack((a_vects.T, np.ones((1, 3))))
    X = np.vstack((x_vects.T, np.ones((1, 3))))
    
    Ainv = np.linalg.inv(A)

    T = np.dot(X, Ainv)

    return T


### TEST
# triA = Delaunay(clust1)
startP = np.array((2, 1.75))
plt.plot(startP[0], startP[1], 'bo')

# scipy.spatial.tsearch(triA, startP)
stackV = lambda vect, i: np.hstack((vect, np.array([i])))
Ttt = transformationMatrixFind(clust1, clust2)

applyP = np.dot(Ttt, stackV(startP, 1))
plt.plot(applyP[0], applyP[1], 'go')

#, clust1, clust2

In [366]:
def warp(targetImage, targetDela, sourceImage, sourceDela):
    assert targetImage.imArr.shape[:2] == sourceImage.imArr.shape[:2]
    midWay = Image("mid_img", np.zeros(list(targetImage.imArr.shape[:2]) + [3]))

    plt.close()
    source_Rchan = scipy.interpolate.interp2d(range(sourceImage.width), range(sourceImage.height), sourceImage.imArr[:,:,0])
    source_Gchan = scipy.interpolate.interp2d(range(sourceImage.width), range(sourceImage.height), sourceImage.imArr[:,:,1])
    source_Bchan = scipy.interpolate.interp2d(range(sourceImage.width), range(sourceImage.height), sourceImage.imArr[:,:,2])

    triangles = targetDela.simplices
    matrices = []
    for i in range(len(triangles)): # range(len(triangles)):
        tri_indexes = triangles[i]
        targetTriangle = targetDela.points[tri_indexes]
        sourceTriangle = sourceDela.points[tri_indexes]

        # plt.triplot(targetTriangle[:, 0], targetTriangle[:, 1], simp, "g-")
        # plt.triplot(sourceTriangle[:, 0], sourceTriangle[:, 1], simp, "r-")

        transf = transformationMatrixFind(targetTriangle, sourceTriangle)

        # matrices.append()
        polyRes = polygon(targetTriangle[:, 0], targetTriangle[:, 1])
    #     print(polyRes)
        Aline = np.vstack((polyRes[0], polyRes[1]))
    #     print(polyRes[0])
    #     print(Aline)


        # plt.plot(Aline[0], Aline[1], 'ro')

        # #     for x in Aline:
        # #         print(" ".join([str(y) for y in x]))
        # #         print()

        Xline = np.dot(transf, np.vstack((Aline, np.ones(Aline.shape[1]))))[:2]
        # plt.plot(Xline[0], Xline[1], 'go')


        for i in range(Aline.shape[1]):
            currA = Aline[:, i]
            currX = Xline[:, i]
            # print(currA, currX)
            midWay.imArr[int(currA[1]), int(currA[0]),:] = [source_Rchan(currX[0], currX[1]), source_Gchan(currX[0], currX[1]), source_Bchan(currX[0], currX[1])]
            
    return midWay

midWay1 = warp(im1, midPtsDela, im1, im1Dela)
midWay2 = warp(im1, midPtsDela, im2, im2Dela)

alpha1 = 0.5
alpha2 = 0.5
assert alpha1 + alpha2 == 1.0

finalMidWayImArr = midWay1.imArr * alpha1 + midWay2.imArr * alpha2
plt.imshow(finalMidWayImArr)

# midWay.imArr


    

In [160]:
plt.close()



# for x in range(midWay.width):
#     for y in range(midWay.height):
#         triIndex = scipy.spatial.tsearch(im1Dela, (x, y))
#         if triIndex >= len(matrices):
#             continue
#         plt.plot(x, y, 'bo')
# #             # after coding, you shouldnt be able to reach here
#         result = np.dot(matrices[triIndex], np.array((x, y, 1)))
#         plt.plot(result[0], result[1], 'go')

KeyboardInterrupt: 

In [127]:
test_tri = Delaunay(results)
x_results = [x[0] for x in results]
y_results = [x[1] for x in results]
plt.triplot(x_results, y_results, test_tri.simplices)
plt.plot(x_results, y_results, 'bo')

test_tri.points[:]= np.dot(test_tri.points, np.roll(np.eye(2), 1, axis=1))
plt.triplot(test_tri.points[:, 0], test_tri.points[:, 1], test_tri.simplices)
plt.plot(test_tri.points[:, 0], test_tri.points[:, 1], 'ro')

NameError: name 'results' is not defined

In [71]:
plt.close()
from scipy import interpolate
import random
x = [0,1,2]
y = [0,3]
z = [[1,2,3], [4,5,6]]
f = interpolate.interp2d(x, y, z, kind='linear')
import matplotlib.pyplot as plt
# xnew = np.arange(-5.01, 5.01, 1e-2)
# ynew = np.arange(-5.01, 5.01, 1e-2)
znew = f([1.4], [2])
znew
#znew = f(xnew, ynew)
# plt.plot(xnew, znew[0, :], 'bo-')
# plt.show()
# znew

array([4.4])

In [162]:
from skimage.draw import polygon
img = np.zeros((10, 10), dtype=np.uint8)
r = np.array([1, 2, 8, 1])
c = np.array([1, 7, 4, 1])
rr, cc = polygon(r, c)
img[rr, cc] = 1
img, rr, cc

(array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8),
 array([2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 7]),
 array([2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 3, 4, 5, 3, 4, 5, 4, 4]))

In [279]:
# r_only = im1.imArr[:,:,0]
# print("r_only:\n", r_only)
# r_flat = r_only.T.reshape(im1.width * im1.height)
r_channel = scipy.interpolate.interp2d(range(im1.width), range(im1.height), im1.imArr[:,:,0])
print(r_chan(0, 1))
print(im1.imArr.shape)

# print(r_flat[im1.width])
meow_start = 0
iSte = 0
# while iSte != im1.height:
#     meow_end = iSte + 1 * im1.width
#     print(r_flat[meow_start:meow_end])
#     print()
#     print(im1.imArr[iSte, :, 0])
#     print("---")
#     meow_start = meow_end
#     iSte +=1
print(im1.imArr[0, 0, 0], im1.imArr[0, 1, 0], im1.imArr[1, 0, 0], im1.imArr[1, 1, 0])

[0.08627451]
(480, 640, 3)
0.10196078431372549 0.07450980392156863 0.08627450980392157 0.0784313725490196


In [241]:
testtt = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

testtt.reshape(testtt.shape[0] * testtt.shape[1], 3)[:, 0]

array([ 1,  4,  7, 10])

In [207]:
(0.10196078 + 0.0745098 + 0.08627451 +  0.07843137) / 4

0.085294115

In [171]:
imInterp = im1
px, py = (0, 0)

red = im1.imArr[:, :, 0]
# blue = im1[:, :, 1]
# green = im1[:, :, 1]
# redPoints = [red[py, px], red[py, px+1], red[py+1, px], red[py+1, px+1]]
redPoints = [0, 1, 2, 3]
r = scipy.interpolate.interp2d([px, px+1], [py, py+1], redPoints)
r(1, 0)

array([2.])